app:
  port: 3000

db:
  host: localhost
  port: 5432
  user: vatrin
  password: vatrin
  name: vatrin

jwt:
  accessToken:
    secret: secret
    expiresIn: 120
  refreshToken:
    secret: secret
    expiresIn: 86400
